/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dialog;

import controlador.Metodos;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Usuario
 */
public class SeleccionarImagen extends javax.swing.JDialog
{

    /**
     * Creates new form SeleccionarImagen
     */
    public SeleccionarImagen(java.awt.Frame parent, boolean modal)
    {
        super(parent, modal);
        initComponents();
        this.fileC_seleccionar.setFileFilter(filtros);
        this.fileC_seleccionar.setMultiSelectionEnabled(false);
    }
    
    public SeleccionarImagen(java.awt.Frame parent, boolean modal,String dui,String doc)
    {
        super(parent, modal);
        initComponents();
        this.fileC_seleccionar.setFileFilter(filtros);
        this.fileC_seleccionar.setMultiSelectionEnabled(false);
        this.doc = doc;
        this.dui = dui;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        fileC_seleccionar = new javax.swing.JFileChooser();
        btn_eliminarLin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        fileC_seleccionar.setBackground(new java.awt.Color(255, 255, 255));
        fileC_seleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileC_seleccionarActionPerformed(evt);
            }
        });

        btn_eliminarLin.setBackground(java.awt.Color.white);
        btn_eliminarLin.setText("Eliminar Imagen");
        btn_eliminarLin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarLinActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fileC_seleccionar, javax.swing.GroupLayout.DEFAULT_SIZE, 683, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_eliminarLin, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(248, 248, 248))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(fileC_seleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_eliminarLin)
                .addGap(0, 15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private FileNameExtensionFilter filtros = new FileNameExtensionFilter(".bmp, .png, .jpg, .jpeg","bmp","png","jpg","jpeg");
    Metodos operacion = new Metodos();
    public String ruta_seleccionada = "",ruta_copia = "";
    String doc = "", dui = "";
    public boolean eliminar = false;
    
    private void fileC_seleccionarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_fileC_seleccionarActionPerformed
    {//GEN-HEADEREND:event_fileC_seleccionarActionPerformed
        JFileChooser seleccion = (JFileChooser) evt.getSource();
        String comando = evt.getActionCommand();
        String r = "";
        if (comando.equals(JFileChooser.APPROVE_SELECTION))
        {
            File ruta = seleccion.getSelectedFile();
            r = ruta.getAbsolutePath();
            String extencion = "";
            if (!r.endsWith("bmp") && !r.endsWith("png") && !r.endsWith("jpg") && !r.endsWith("jpeg"))
            {
               JOptionPane.showMessageDialog(null,"El archivo a seleccionar debe ser formato bmp,png,jpg o jpeg");
            }
            else
            {
                if (r.endsWith("bmp"))
                    extencion = "bmp";
                if (r.endsWith("png"))
                    extencion = "png";
                if (r.endsWith("jpg"))
                    extencion = "jpg";
                if (r.endsWith("jpeg"))
                    extencion = "jpeg";
                operacion.CrearCarpeta("Copias\\"+dui+"\\"+doc);
                ruta_copia = operacion.GenerarRutaAbsoluta("Copias\\"+dui+"\\"+doc+"\\"+dui+"_"+doc+"."+extencion);
                operacion.copiar_pegar_archivo(ruta, new File(ruta_copia));
                ruta_seleccionada = ruta.getAbsolutePath();
                this.dispose();
            }
        }
        else
        {
            this.dispose();
        }
    }//GEN-LAST:event_fileC_seleccionarActionPerformed

    private void btn_eliminarLinActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btn_eliminarLinActionPerformed
    {//GEN-HEADEREND:event_btn_eliminarLinActionPerformed
        eliminar = true;
        this.dispose();
    }//GEN-LAST:event_btn_eliminarLinActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(SeleccionarImagen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(SeleccionarImagen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(SeleccionarImagen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(SeleccionarImagen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                SeleccionarImagen dialog = new SeleccionarImagen(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter()
                {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e)
                    {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_eliminarLin;
    private javax.swing.JFileChooser fileC_seleccionar;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
