package Vistas.Login;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import Vistas.Apariencia.NimbusApariencia;
import com.sun.awt.AWTUtilities;
import controlador.DatosSesion;
import controlador.Metodos;
import java.awt.Menu;
import java.awt.Shape;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.geom.RoundRectangle2D;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import menu.menuPrincipal;

/**
 *
 * @author Chappie
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form IniciarSesion
     */
    public Login() {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NimbusApariencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NimbusApariencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NimbusApariencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NimbusApariencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        initComponents();

         try {
             setIconImage(new ImageIcon(getClass().getResource("/images/logopng.png")).getImage());
        } catch (Exception e) {
        }
        //
        Shape forma = new RoundRectangle2D.Double(0, 0, getBounds().width, getBounds().height, 20, 20);
        AWTUtilities.setWindowShape(this, forma);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnIngresar = new javax.swing.JButton();
        txt_usuario = new javax.swing.JTextField();
        txt_clave = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jcMousePanel1 = new jcMousePanel.jcMousePanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Gotham Thin", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(225, 94, 29));
        jLabel4.setText("NOMBRE USUARIO");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLabel5.setFont(new java.awt.Font("Gotham Thin", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(225, 94, 29));
        jLabel5.setText("CONTRASEÑA");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        btnIngresar.setBackground(new java.awt.Color(135, 81, 19));
        btnIngresar.setFont(new java.awt.Font("Gotham Extra Light", 0, 18)); // NOI18N
        btnIngresar.setForeground(new java.awt.Color(248, 208, 10));
        btnIngresar.setText("Ingresar");
        btnIngresar.setBorderPainted(false);
        btnIngresar.setContentAreaFilled(false);
        btnIngresar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnIngresar.setFocusPainted(false);
        btnIngresar.setFocusable(false);
        btnIngresar.setRequestFocusEnabled(false);
        btnIngresar.setVerifyInputWhenFocusTarget(false);
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        jPanel2.add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, 210, 60));

        txt_usuario.setBackground(new java.awt.Color(0, 0, 0));
        txt_usuario.setFont(new java.awt.Font("Gotham Thin", 0, 18)); // NOI18N
        txt_usuario.setForeground(new java.awt.Color(251, 220, 5));
        txt_usuario.setBorder(null);
        txt_usuario.setCaretColor(new java.awt.Color(73, 181, 172));
        jPanel2.add(txt_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 310, 40));

        txt_clave.setBackground(new java.awt.Color(0, 0, 0));
        txt_clave.setFont(txt_clave.getFont().deriveFont(txt_clave.getFont().getSize()+7f));
        txt_clave.setForeground(new java.awt.Color(251, 220, 5));
        txt_clave.setBorder(null);
        txt_clave.setCaretColor(new java.awt.Color(73, 181, 172));
        txt_clave.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_claveKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_claveKeyTyped(evt);
            }
        });
        jPanel2.add(txt_clave, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 310, 36));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 310, 10));

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 310, 10));

        jLabel9.setFont(new java.awt.Font("Gotham Thin", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(225, 94, 29));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("x");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel9MousePressed(evt);
            }
        });
        jLabel9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel9KeyPressed(evt);
            }
        });
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 30, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 400, 500));

        jcMousePanel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.jpg"))); // NOI18N
        getContentPane().add(jcMousePanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents
Metodos m = new Metodos();
    String sql = "";

    void logeo() {
        String bloc[] = null;
//        String numeroMaquina = "";
//        String caja = "";
//        String sucursal = "";
//        String ip = "";
//        String usuariobd = "";
//        String clavebd = "";
//        String puerto = "";
//        String bd="";
//
//        //maquina 0
//        //caja  1
//        //sucursal 2
//        try {
//            bloc = m.leerTxt("C:\\Windows\\configv.txt").split("-");
//            numeroMaquina = bloc[0];
//
//        } catch (Exception e) {
//            bloc = null;
//            numeroMaquina = "";
//        }
//        if (bloc[0].isEmpty() || bloc == null) {
//            JOptionPane.showMessageDialog(null, "ERROR I-AFW");
//        } else {
//            DatosSesion.numeroMaquina = numeroMaquina;
//            sucursal = bloc[2];
//            ip = bloc[3];
//            usuariobd = bloc[4];
//            clavebd = bloc[5];
//            puerto = bloc[6];
//            bd=bloc[7];
//
//            System.out.println("esta es la sucursal" + sucursal);
//            System.out.println(ip);
//            System.out.println(usuariobd);
//            System.out.println(clavebd);
//            System.out.println(puerto);
//
//            DatosSesion.ip = ip;
//            DatosSesion.bduser = usuariobd;
//            DatosSesion.bdpassr = clavebd;
//            DatosSesion.puerto = puerto;
//            DatosSesion.bd=bd;
//
//            DatosSesion.cod_sucursal = sucursal;
//            String usuario = "", clave = "";
//            usuario = txt_usuario.getText();
//            clave = txt_clave.getText();
//            
//            DatosSesion.nom_suc=m.obtener_codigoDeCampo("select * from sucursales where idSucursal='"+sucursal+"'","nombre");
//            
//            sql = "select * from empleados where  BINARY usuario='" + usuario + "' and BINARY clave='" + clave + "' and estado='ACTIVO' and idSucursal='" + sucursal + "'";
//
//            if (m.SiRegistroExiste(sql)) {
//
//                String datos[] = m.obtener_codigoDeCampo(sql, new String[]{"nombre", "idEmpleado", "nivel", "idSucursal"});
//                DatosSesion.cod_empleado = datos[1];
//                DatosSesion.nombre_empleado = datos[0];
//
//                DatosSesion.nivel = datos[2];
//
//                String nivel = datos[2];
//
//                try {
//                    sql = "select * from corte where  idSucursal='" + sucursal + "' and estado='ABIERTO' order by apertura desc limit 1 ";
//                    if (m.SiRegistroExiste(sql)) {
//                        String[] dat = m.obtener_codigoDeCampo(sql, new String[]{"idCorte", "apertura"});
//                        DatosSesion.IDCORTE = dat[0];
//
//                        DatosSesion.fechasistema = dat[1];
//                    } else {
//                        DatosSesion.fechasistema = "";
//                    }
//                } catch (Exception e) {
//                }
//
//                sql = "select * from cajas where idEmpleado='" + datos[1] + "'";
//                if (m.SiRegistroExiste(sql)) {
//                    DatosSesion.numeroCaja = m.obtener_codigoDeCampo(sql, "idNumCaja");
//                }
//                //fecha para mientras
//                switch (nivel) {
//                   
//
//                }
//
//            } else {
//                JOptionPane.showMessageDialog(null, "ACCESO DENEGAGO \n VERIFIQUE QUE SUS CREDENCIALES \n ESTEN BIEN"
//                        + " ESCRITAS( SENSIBLE A MINUSCULAS Y MAYUSCULAS )");
//            }
//
//        }
        this.dispose();
        menuPrincipal m = new menuPrincipal();
        m.setLocationRelativeTo(null);
        m.setVisible(true);
    }

    private void jLabel9KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel9KeyPressed

    }//GEN-LAST:event_jLabel9KeyPressed

    private void jLabel9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MousePressed
        System.exit(0);
    }//GEN-LAST:event_jLabel9MousePressed

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        logeo();
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void txt_claveKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_claveKeyTyped
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            logeo();
        }
    }//GEN-LAST:event_txt_claveKeyTyped

    private void txt_claveKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_claveKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            logeo();
        }
    }//GEN-LAST:event_txt_claveKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private jcMousePanel.jcMousePanel jcMousePanel1;
    private javax.swing.JPasswordField txt_clave;
    private javax.swing.JTextField txt_usuario;
    // End of variables declaration//GEN-END:variables
}
